# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current_affairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_heading', models.CharField(max_length=250)),
                ('yellow_heading', models.CharField(max_length=250)),
                ('key_1', models.CharField(max_length=200)),
                ('key_2', models.CharField(max_length=200)),
                ('key_3', models.CharField(max_length=200)),
                ('key_4', models.CharField(blank=True, max_length=200, null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, default='', null=True)),
                ('all_key_points', models.TextField(blank=True, default='', null=True)),
                ('Science_Techonlogy', models.BooleanField(db_index=True, default=False)),
                ('National', models.BooleanField(db_index=True, default=False)),
                ('State', models.BooleanField(db_index=True, default=False)),
                ('International', models.BooleanField(db_index=True, default=False)),
                ('Business_Economy_Banking', models.BooleanField(db_index=True, default=False)),
                ('Environment', models.BooleanField(db_index=True, default=False)),
                ('Defence', models.BooleanField(db_index=True, default=False)),
                ('Persons_in_News', models.BooleanField(db_index=True, default=False)),
                ('Awards_Honours', models.BooleanField(db_index=True, default=False)),
                ('Sports', models.BooleanField(db_index=True, default=False)),
                ('Art_Culture', models.BooleanField(db_index=True, default=False)),
                ('Government_Schemes', models.BooleanField(default=False)),
                ('ca_img', models.FileField(upload_to='ca/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='current_affairs_slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_heading', models.CharField(max_length=50)),
                ('yellow_heading', models.CharField(max_length=50)),
                ('key_1', models.CharField(max_length=50)),
                ('key_2', models.CharField(max_length=50)),
                ('key_3', models.CharField(max_length=50)),
                ('key_4', models.CharField(blank=True, max_length=50, null=True)),
                ('day', models.DateField(default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('ca_image', models.FileField(upload_to='current_affairs/%Y/%m/%d')),
            ],
        ),
  
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_current_affairs', models.IntegerField(db_index=True, default=3)),
                ('total_current_affairs_page', models.IntegerField(db_index=True, default=3)),
                ('Science_Techonlogy', models.IntegerField(db_index=True, default=0)),
                ('National', models.IntegerField(db_index=True, default=0)),
                ('State', models.IntegerField(db_index=True, default=0)),
                ('International', models.IntegerField(db_index=True, default=0)),
                ('Business_Economy_Banking', models.IntegerField(db_index=True, default=0)),
                ('Environment', models.IntegerField(db_index=True, default=0)),
                ('Defence', models.IntegerField(db_index=True, default=0)),
                ('Persons_in_News', models.IntegerField(db_index=True, default=0)),
                ('Awards_Honours', models.IntegerField(db_index=True, default=0)),
                ('Sports', models.IntegerField(db_index=True, default=0)),
                ('Art_Culture', models.IntegerField(db_index=True, default=0)),
                ('Government_Schemes', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
