# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='the_economy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=150)),
                ('meaning', models.CharField(blank=True, max_length=650, null=True)),
                ('example', models.CharField(blank=True, max_length=650, null=True)),
                ('synonym', models.CharField(blank=True, max_length=600, null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('word_img', models.FileField(blank=True, null=True, upload_to='word/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='the_hindu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=150)),
                ('meaning', models.CharField(blank=True, max_length=650, null=True)),
                ('example', models.CharField(blank=True, max_length=650, null=True)),
                ('synonym', models.CharField(blank=True, max_length=600, null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('word_img', models.FileField(blank=True, null=True, upload_to='word/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
