# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20170609_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_english',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_the_hindu_word_list1', models.IntegerField(db_index=True, default=0)),
                ('total_the_hindu_word_list2', models.IntegerField(db_index=True, default=0)),
                ('total_the_hindu_header1', models.IntegerField(db_index=True, default=0)),
                ('total_the_hindu_header2', models.IntegerField(db_index=True, default=0)),
                ('total_the_economy_word_list1', models.IntegerField(db_index=True, default=0)),
                ('total_the_economy_word_list2', models.IntegerField(db_index=True, default=0)),
                ('total_the_economy_header1', models.IntegerField(db_index=True, default=0)),
                ('total_the_economy_header2', models.IntegerField(db_index=True, default=0)),
                ('total_page', models.IntegerField(db_index=True, default=0)),
                ('no_of_hindu_today', models.IntegerField(db_index=True, default=0)),
                ('no_of_economy_today', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
