# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_total_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_english',
            name='test',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
