# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_total_english_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='the_economy_word_header2',
            old_name='Heading_for_list1',
            new_name='Heading_for_list2',
        ),
        migrations.RenameField(
            model_name='the_hindu_word_header2',
            old_name='Heading_for_list1',
            new_name='Heading_for_list2',
        ),
    ]
