# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20170610_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='profit_n_loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_image', models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question')),
                ('one', models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question')),
                ('two', models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question')),
                ('three', models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question')),
                ('four', models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question')),
                ('five', models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question')),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, db_index=True, null=True)),
                ('a', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('a_img', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('b', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('b_img', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('c', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('c_img', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('d', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('e', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('d_img', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('solution', models.TextField()),
                ('solution_image', models.FileField(blank=True, null=True, upload_to='word/%Y/%m/%d')),
                ('solution_one', models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/solution')),
                ('solution_two', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('solution_three', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('solution_four', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('solution_five', models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d')),
                ('level', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ans', models.IntegerField(default=1)),
            ],
        ),
    ]
