# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_profit_n_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_n_loss',
            name='e_img',
            field=models.FileField(blank=True, null=True, upload_to='profit_n_loss/%Y/%m/%d'),
        ),
    ]
