# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_profit_n_loss_e_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit_n_loss',
            name='level',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
    ]
