# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20170618_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_n_loss',
            name='new_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
    ]
