# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_profit_n_loss_new_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_n_loss',
            name='use_image',
            field=models.IntegerField(default=0),
        ),
    ]
