# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_profit_n_loss_use_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit_n_loss', models.IntegerField(db_index=True, default=5)),
                ('total_profit_n_loss_page', models.IntegerField(db_index=True, default=5)),
            ],
        ),
    ]
