# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_total_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_n_loss',
            name='shortcut',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profit_n_loss',
            name='shortcut_image',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/short'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='a_img',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='b_img',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='c_img',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='d_img',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='e_img',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/question'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='solution_five',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/solution'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='solution_four',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/solution'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='solution_three',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/solution'),
        ),
        migrations.AlterField(
            model_name='profit_n_loss',
            name='solution_two',
            field=models.FileField(blank=True, null=True, upload_to='math/profit_n_loss/%Y/%m/%d/solution'),
        ),
    ]
