# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20170618_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='current_affairs',
            options={'ordering': ['-day']},
        ),
    ]
