# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20170618_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit_n_loss',
            name='ans',
        ),
        migrations.AddField(
            model_name='profit_n_loss',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
