# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_auto_20170628_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_n_loss',
            name='ans',
            field=models.IntegerField(default=1),
        ),
    ]
