# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_profit_n_loss_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('yellow_heading', models.CharField(max_length=250)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('first_day', models.DateField(db_index=True, default=datetime.date.today)),
                ('last_day', models.DateField(db_index=True, default=datetime.date.today)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True)),
                ('eligibility', models.TextField(blank=True, default='', null=True)),
                ('age', models.TextField(blank=True, default='', null=True)),
                ('amount', models.TextField(blank=True, default='', null=True)),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], default='JANUARY', max_length=9)),
                ('all_key_points', models.TextField(blank=True, default='', null=True)),
                ('Science_Techonlogy', models.BooleanField(db_index=True, default=False)),
                ('National', models.BooleanField(db_index=True, default=False)),
                ('State', models.BooleanField(db_index=True, default=False)),
                ('International', models.BooleanField(db_index=True, default=False)),
                ('Business_Economy_Banking', models.BooleanField(db_index=True, default=False)),
                ('Environment', models.BooleanField(db_index=True, default=False)),
                ('Defence', models.BooleanField(db_index=True, default=False)),
                ('Persons_in_News', models.BooleanField(db_index=True, default=False)),
                ('Awards_Honours', models.BooleanField(db_index=True, default=False)),
                ('Sports', models.BooleanField(db_index=True, default=False)),
                ('Art_Culture', models.BooleanField(db_index=True, default=False)),
                ('Government_Schemes', models.BooleanField(default=False)),
                ('ca_img', models.FileField(upload_to='ca/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
