# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Art_Culture',
            new_name='agriculture',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Awards_Honours',
            new_name='b_tech',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='all_key_points',
            new_name='extra_day',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Business_Economy_Banking',
            new_name='iti',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Defence',
            new_name='law',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Environment',
            new_name='m_phil',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='International',
            new_name='m_tech',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='National',
            new_name='mba',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Persons_in_News',
            new_name='medical',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Science_Techonlogy',
            new_name='phd',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Sports',
            new_name='tenth',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='State',
            new_name='twelth',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Government_Schemes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='month',
        ),
        migrations.RemoveField(
            model_name='job',
            name='yellow_heading',
        ),
        migrations.AddField(
            model_name='job',
            name='graduation',
            field=models.CharField(blank=True, choices=[('any', 'ANY'), ('b_com', 'B Com'), ('b_ed', 'B Ed'), ('b_pharm', 'B Pharm'), ('b_sc', 'B Sc'), ('bba', 'BBA'), ('bca', 'BCA'), ('bds', 'BDS'), ('b_tech', 'B Tech'), ('llb', 'LLB'), ('ca', 'CA'), ('cs', 'CS'), ('b_tech/bca', 'B Tech OR Bca'), ('mbbs', 'MBBS'), ('bds', 'BDS')], db_index=True, default='any', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='master',
            field=models.CharField(blank=True, choices=[('any', 'ANY'), ('m_com', 'M Com'), ('M_ed', 'M Ed'), ('M_pharm', 'M Pharm'), ('M_sc', 'M Sc'), ('mba', 'MBA'), ('mca', 'MCA'), ('m_phil', 'M Phil'), ('m_tech', 'M Tech')], db_index=True, default='any', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, choices=[('any', 'ANY'), ('andaman_nicobar', 'Andaman & Nicobar'), ('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chandigarh', 'Chandigarh'), ('chattisgarh', 'Chhattisgarh'), ('dadra_nagar_haveli', 'Dadra &Nagar Haveli'), ('daman_diu', 'Daman & Diu'), ('delhi', 'Delhi'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jammu_kashmir', 'Jammu & Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('orissa', 'Orissa'), ('puducherry', 'Puducherry'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], db_index=True, default='any', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
