# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20170704_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='law',
            new_name='M_ed',
        ),
        migrations.AddField(
            model_name='job',
            name='M_pharm',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='M_sc',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='b_com',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='b_ed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='b_pharm',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='b_sc',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='bba',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='bca',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='bds',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='ca',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='cs',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='llb',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='m_com',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='mbbs',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='mca',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='post_g',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='graduation',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('any', 'ANY'), ('b_com', 'B Com'), ('b_ed', 'B Ed'), ('b_pharm', 'B Pharm'), ('b_sc', 'B Sc'), ('bba', 'BBA'), ('bca', 'BCA'), ('bds', 'BDS'), ('b_tech', 'B Tech'), ('llb', 'LLB'), ('ca', 'CA'), ('cs', 'CS'), ('b_tech/bca', 'B Tech OR Bca'), ('mbbs', 'MBBS'), ('bds', 'BDS')], db_index=True, default='any', max_length=20, null=True),
        ),
    ]
