# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_auto_20170704_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='master',
        ),
        migrations.AddField(
            model_name='job',
            name='graduate_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
