# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_auto_20170704_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ca_img',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('any', 'ANY'), ('bank', 'BANK'), ('ssc', 'SSC'), ('upsc', 'UPSC'), ('rail', 'RAIL'), ('other', 'OTHER')], db_index=True, default='any', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='des',
            field=models.FileField(blank=True, null=True, upload_to='job/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, choices=[('all_india', 'ALL INDIA'), ('andaman_nicobar', 'Andaman & Nicobar'), ('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chandigarh', 'Chandigarh'), ('chattisgarh', 'Chhattisgarh'), ('dadra_nagar_haveli', 'Dadra &Nagar Haveli'), ('daman_diu', 'Daman & Diu'), ('delhi', 'Delhi'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jammu_kashmir', 'Jammu & Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('orissa', 'Orissa'), ('puducherry', 'Puducherry'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], db_index=True, default='any', max_length=50, null=True),
        ),
    ]
