# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_auto_20170704_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('any', 'ANY'), ('bank', 'BANK'), ('ssc', 'SSC'), ('upsc', 'UPSC'), ('rail', 'RAIL'), ('defence', 'DEFENCE'), ('other', 'OTHER')], db_index=True, default='other', max_length=50, null=True),
        ),
    ]
