# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_auto_20170704_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_job', models.IntegerField(default=3)),
                ('total_job_page', models.IntegerField(default=3)),
                ('total_bank', models.IntegerField(default=3)),
                ('total_bank_page', models.IntegerField(default=3)),
                ('total_upsc', models.IntegerField(default=0)),
                ('total_upsc_page', models.IntegerField(default=0)),
                ('total_railway', models.IntegerField(default=0)),
                ('total_railway_page', models.IntegerField(default=0)),
                ('total_ssc', models.IntegerField(default=0)),
                ('total_ssc_page', models.IntegerField(default=0)),
                ('total_defence', models.IntegerField(default=0)),
                ('total_defence_page', models.IntegerField(default=0)),
                ('total_other', models.IntegerField(default=0)),
                ('total_other_page', models.IntegerField(default=0)),
            ],
        ),
    ]
