# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_total_job_category_total_job_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='M_ed',
            new_name='m_ed',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='M_pharm',
            new_name='m_pharm',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='M_sc',
            new_name='m_sc',
        ),
    ]
