# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_auto_20170706_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ca_img',
            field=models.FileField(blank=True, null=True, upload_to='job/%Y/%m/%d'),
        ),
    ]
