# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_job_ca_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='top',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
