# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_job_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='detail_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
