# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0030_auto_20170709_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='detail_link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
