# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_auto_20170709_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.TextField(blank=True, default='Gen:\\\\OBC:\\\\Sc:\\\\St:\\\\ph:', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='amount',
            field=models.CharField(blank=True, default='Gen:\\\\OBC:\\\\Sc:\\\\St:\\\\ph:', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='detail_link',
            field=models.CharField(blank=True, default='#', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='eligibility',
            field=models.TextField(blank=True, default='Graduate', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='extra_day',
            field=models.TextField(blank=True, default='Admit Download:\\\\preliminary Exam:\\\\Main Exam:\\\\Result of Preliminary Exam:\\\\Result of Main Exam:', null=True),
        ),
    ]
