# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0032_auto_20170709_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_job',
            old_name='total_railway',
            new_name='total_rail',
        ),
        migrations.RenameField(
            model_name='total_job',
            old_name='total_railway_page',
            new_name='total_rail_page',
        ),
    ]
