# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0033_auto_20170711_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eighth',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
