# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0034_job_eighth'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_job_category',
            name='total_eighth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='total_job_category',
            name='total_eighth_page',
            field=models.IntegerField(default=0),
        ),
    ]
