# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0035_auto_20170711_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deploma',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='total_job_category',
            name='total_deploma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='total_job_category',
            name='total_deploma_page',
            field=models.IntegerField(default=0),
        ),
    ]
