# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0036_auto_20170711_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_job_category',
            name='total_llm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='total_job_category',
            name='total_llm_page',
            field=models.IntegerField(default=0),
        ),
    ]
