# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0037_auto_20170712_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='llm',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
