# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0038_job_llm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_job_state',
            old_name='total_jharkhand_com_page',
            new_name='total_jharkhand_page',
        ),
        migrations.AddField(
            model_name='total_job_state',
            name='total_lakshadweep',
            field=models.IntegerField(default=0),
        ),
    ]
