# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0039_auto_20170712_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1_day', models.DateField(blank=True, db_index=True, null=True)),
                ('word2_day', models.DateField(blank=True, db_index=True, null=True)),
                ('word_e1_day', models.DateField(blank=True, db_index=True, null=True)),
                ('word_e2_day', models.DateField(blank=True, db_index=True, null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='home/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
