# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0041_auto_20170716_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='the_economy_word_list1',
            name='link',
        ),
        migrations.RemoveField(
            model_name='the_economy_word_list2',
            name='link',
        ),
        migrations.RemoveField(
            model_name='the_hindu_word_list1',
            name='link',
        ),
        migrations.RemoveField(
            model_name='the_hindu_word_list2',
            name='link',
        ),
        migrations.AddField(
            model_name='the_economy_word_header1',
            name='link',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='the_economy_word_header2',
            name='link',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='the_hindu_word_header1',
            name='link',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='the_hindu_word_header2',
            name='link',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
