# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0042_auto_20170716_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_image', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('one', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('two', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('three', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('four', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('five', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, db_index=True, null=True)),
                ('a', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('a_img', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('b', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('b_img', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('c', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('c_img', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('d', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('d_img', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('e', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('e_img', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/question')),
                ('solution', models.TextField()),
                ('solution_image', models.FileField(blank=True, null=True, upload_to='word/%Y/%m/%d')),
                ('solution_one', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/solution')),
                ('solution_two', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/solution')),
                ('solution_three', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/solution')),
                ('solution_four', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/solution')),
                ('solution_five', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/solution')),
                ('level', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('ans', models.IntegerField(default=1)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('shortcut', models.TextField(blank=True, null=True)),
                ('shortcut_image', models.FileField(blank=True, null=True, upload_to='math/math/%Y/%m/%d/short')),
                ('use_image', models.IntegerField(default=0)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('chapter', models.CharField(blank=True, choices=[('profit_n_loss', 'profit_n_loss'), ('squre_n_cube', 'Andaman & Nicobar'), ('simplification', 'Andhra Pradesh'), ('average', 'Arunachal Pradesh'), ('percentage', 'Assam'), ('problem_on_age', 'Bihar'), ('ratio_n_proportion', 'Chandigarh'), ('partnership', 'Chhattisgarh'), ('time_n_work', 'Dadra &Nagar Haveli'), ('pipe_cistern', 'Daman & Diu'), ('time_n_distance', 'Delhi'), ('problem_on_age', 'problem_on_age'), ('boats_n_stream', 'Gujarat'), ('alligation_n_mixture', 'Haryana'), ('simple_interest', 'Himachal Pradesh'), ('compound_interest', 'Jammu & Kashmir'), ('volume_n_surface_area', 'Karnataka'), ('probability', 'Kerala'), ('permutation_combination', 'Madhya Pradesh'), ('bar_graph', 'Maharashtra'), ('pie_charts', 'Manipur'), ('line_graph', 'Meghalaya')], db_index=True, default='any', max_length=50, null=True)),
            ],
            options={
                'ordering': ['day', 'creation_time'],
            },
        ),
        migrations.DeleteModel(
            name='profit_n_loss',
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_alligation_n_mixture',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_alligation_n_mixture_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_average',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_average_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_bar_graph',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_bar_graph_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_boats_n_stream',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_boats_n_stream_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_compound_interest',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_compound_interest_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_line_graph',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_line_graph_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_partnership',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_partnership_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_percentage',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_percentage_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_permutation_combination',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_permutation_combination_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_pie_charts',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_pie_charts_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_pipe_cistern',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_pipe_cistern_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_probability',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_probability_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_problem_on_age',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_problem_on_age_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_ptime_n_work_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_ratio_n_proportion',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_ratio_n_proportion_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_simple_interest',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_simple_interest_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_simplification',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_simplification_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_squre_n_cube',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_squre_n_cube_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_time_n_distance',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_time_n_distance_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_time_n_work',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_volume_n_surface_area',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddField(
            model_name='total_math',
            name='total_volume_n_surface_area_page',
            field=models.IntegerField(db_index=True, default=5),
        ),
    ]
