# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0043_auto_20170716_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='chapter',
            field=models.CharField(blank=True, choices=[('profit_n_loss', 'profit_n_loss'), ('squre_n_cube', 'squre_n_cube'), ('simplification', 'simplification'), ('average', 'average'), ('percentage', 'percentage'), ('problem_on_age', 'problem_on_age'), ('ratio_n_proportion', 'ratio_n_proportion'), ('partnership', 'partnership'), ('time_n_work', 'time_n_work'), ('pipe_cistern', 'pipe_cistern'), ('time_n_distance', 'time_n_distance'), ('problem_on_age', 'problem_on_age'), ('boats_n_stream', 'boats_n_stream'), ('alligation_n_mixture', 'alligation_n_mixture'), ('simple_interest', 'simple_interest'), ('compound_interest', 'compound_interest'), ('volume_n_surface_area', 'volume_n_surface_area'), ('probability', 'probability'), ('permutation_combination', 'permutation_combination'), ('bar_graph', 'bar_graph'), ('pie_charts', 'pie_charts'), ('line_graph', 'line_graph')], db_index=True, default='any', max_length=50, null=True),
        ),
    ]
