# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0044_auto_20170716_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
