# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0045_math_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(db_index=True, max_length=150)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='topic/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='user_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=150)),
                ('section', models.CharField(blank=True, max_length=650, null=True)),
                ('headline', models.CharField(blank=True, max_length=650, null=True)),
                ('date_added', models.DateField(db_index=True, default=datetime.date.today)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('img_link', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('creation_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
