# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0046_topic_user_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_save',
            name='link_id',
            field=models.CharField(blank=True, max_length=650, null=True),
        ),
    ]
