# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0048_reasoning_total_reasoning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_reasoning',
            old_name='total_seating_arrengment',
            new_name='total_seating_arrangment',
        ),
        migrations.RenameField(
            model_name='total_reasoning',
            old_name='total_seating_arrengment_page',
            new_name='total_seating_arrangment_page',
        ),
        migrations.AlterField(
            model_name='reasoning',
            name='chapter',
            field=models.CharField(blank=True, choices=[('analogy', 'analogy'), ('classification', 'classification'), ('alpha_numaric_symbol', 'alpha_numaric_symbol'), ('coding_decoding', 'coding_decoding'), ('fictious_symbol', 'fictious_symbol'), ('seating_arrangment', 'seating_arrangment'), ('Ranking_test', 'Ranking_test'), ('inequality_and_coded_inequality', 'inequality_and_coded_inequality'), ('input_output', 'input_output'), ('circle_puzzle', 'circle_puzzle'), ('squere_puzzle', 'squere_puzzle'), ('flore_puzzle', 'flore_puzzle'), ('blood_relation', 'blood_relation'), ('coded_relationship', 'coded_relationship'), ('decision_making', 'decision_making'), ('syllogism', 'syllogism'), ('clock', 'clock'), ('calender', 'calender'), ('arguments', 'arguments'), ('cause_n_effect', 'cause_n_effect'), ('direction_test', 'direction_test')], db_index=True, default='any', max_length=50, null=True),
        ),
    ]
