# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0049_auto_20170721_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoning',
            name='question_part',
            field=models.TextField(blank=True, null=True),
        ),
    ]
