# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0050_reasoning_question_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasoning',
            name='question_part',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
