# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0051_auto_20170722_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasoning',
            options={'ordering': ['-day', 'creation_time']},
        ),
        migrations.AlterField(
            model_name='reasoning',
            name='ans',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
