# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0052_auto_20170726_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_part', models.TextField(blank=True, default='', null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, db_index=True, null=True)),
                ('a', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('b', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('c', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('d', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('e', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('solution', models.TextField()),
                ('level', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('ans', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('home', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-day', 'creation_time'],
            },
        ),
        migrations.CreateModel(
            name='error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_part', models.TextField(blank=True, default='', null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, db_index=True, null=True)),
                ('a', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('b', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('c', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('d', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('e', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('solution', models.TextField()),
                ('level', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('ans', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('chapter', models.CharField(blank=True, choices=[('noun', 'noun'), ('pronoun', 'pronoun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('interjection', 'interjection'), ('conjunction', 'conjunction'), ('preposition', 'preposition'), ('misl', 'misl'), ('article', 'article'), ('number', 'number'), ('flore_puzzle', 'flore_puzzle'), ('blood_relation', 'blood_relation'), ('coded_relationship', 'coded_relationship'), ('decision_making', 'decision_making'), ('syllogism', 'syllogism'), ('clock', 'clock'), ('calender', 'calender'), ('arguments', 'arguments'), ('cause_n_effect', 'cause_n_effect'), ('direction_test', 'direction_test')], db_index=True, default='any', max_length=50, null=True)),
                ('home', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-day', 'creation_time'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
