# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0053_auto_20170727_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_close', models.IntegerField(db_index=True, default=5)),
                ('total_close_page', models.IntegerField(db_index=True, default=5)),
            ],
        ),
        migrations.CreateModel(
            name='total_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_noun', models.IntegerField(db_index=True, default=5)),
                ('total_noun_page', models.IntegerField(db_index=True, default=5)),
                ('total_pronoun', models.IntegerField(db_index=True, default=5)),
                ('total_pronoun_page', models.IntegerField(db_index=True, default=5)),
                ('total_verb', models.IntegerField(db_index=True, default=5)),
                ('total_verb_page', models.IntegerField(db_index=True, default=5)),
                ('total_adjective', models.IntegerField(db_index=True, default=5)),
                ('total_adjective_page', models.IntegerField(db_index=True, default=5)),
                ('total_adverb', models.IntegerField(db_index=True, default=5)),
                ('total_adverb_page', models.IntegerField(db_index=True, default=5)),
                ('total_interjection', models.IntegerField(db_index=True, default=5)),
                ('total_interjection_page', models.IntegerField(db_index=True, default=5)),
                ('total_conjunction', models.IntegerField(db_index=True, default=5)),
                ('total_conjunction_page', models.IntegerField(db_index=True, default=5)),
                ('total_preposition', models.IntegerField(db_index=True, default=5)),
                ('total_preposition_page', models.IntegerField(db_index=True, default=5)),
                ('total_miscellaneous', models.IntegerField(db_index=True, default=5)),
                ('total_miscellaneous_page', models.IntegerField(db_index=True, default=5)),
                ('total_article', models.IntegerField(db_index=True, default=5)),
                ('total_article_page', models.IntegerField(db_index=True, default=5)),
                ('total_number', models.IntegerField(db_index=True, default=5)),
                ('total_number_page', models.IntegerField(db_index=True, default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='error',
            name='chapter',
            field=models.CharField(blank=True, choices=[('noun', 'noun'), ('pronoun', 'pronoun'), ('verb', 'verb'), ('adjective', 'adjective'), ('adverb', 'adverb'), ('interjection', 'interjection'), ('conjunction', 'conjunction'), ('preposition', 'preposition'), ('miscellaneous', 'miscellaneous'), ('article', 'article'), ('number', 'number')], db_index=True, default='any', max_length=50, null=True),
        ),
    ]
