# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0055_auto_20170727_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='loop',
        ),
        migrations.AddField(
            model_name='close',
            name='loop',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
