# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0056_auto_20170727_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='close',
            name='f',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='close',
            name='g',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='close',
            name='h',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='close',
            name='i',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='close',
            name='j',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
