# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0057_auto_20170727_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='close',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
