# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0059_auto_20170730_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='new_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
    ]
