# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0060_auto_20170730_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='f',
        ),
        migrations.RemoveField(
            model_name='error',
            name='g',
        ),
        migrations.RemoveField(
            model_name='error',
            name='h',
        ),
        migrations.RemoveField(
            model_name='error',
            name='i',
        ),
        migrations.RemoveField(
            model_name='error',
            name='j',
        ),
    ]
