# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0062_auto_20170730_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
