# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0063_auto_20170730_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-day', '-creation_time']},
        ),
        migrations.AlterField(
            model_name='job',
            name='age',
            field=models.TextField(blank=True, default='Gen: ///OBC: ///Sc: ///ST: ///PH:', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='amount',
            field=models.CharField(blank=True, default='Gen: ///OBC: ///Sc: ///ST: ///PH:', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='extra_day',
            field=models.TextField(blank=True, default='Admit Download: /// preliminary Exam: ///Main Exam: ///Result of Preliminary Exam: ///Result of Main Exam:', null=True),
        ),
    ]
