# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0064_auto_20170806_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_affairs',
            name='link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='current_affairs',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
