# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-01 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0066_auto_20190501_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='a',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
