"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l*mslyvw)$!badv$$(6)-oycvns0)5yv@6q7c@-%v8mfbga#5i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','128.199.25.40']

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'www.rana07@gmail.com'
EMAIL_HOST_PASSWORD = 'mourana@#@#'
EMAIL_PORT = 587
# Application definition

INSTALLED_APPS = (
'bank',
'genai',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
)
MIDDLEWARE = MIDDLEWARE_CLASSES
ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'post',                      
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
        'ATOMIC_REQUESTS': True,
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c timezone=UTC',
            'isolation_level': 1,  # Read Committed
        }
    },
    'sql': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Disable UTC timezone assertion for Windows PostgreSQL (development only)
import psycopg2
from psycopg2 import extensions
psycopg2.extensions.register_adapter(str, lambda x: extensions.QuotedString(x))

# Monkey patch Django's utc_tzinfo_factory to skip UTC validation on Windows
import django.db.backends.postgresql.utils as pg_utils
original_utc_tzinfo = pg_utils.utc_tzinfo_factory

def utc_tzinfo_factory_patched(conn):
    """Skip UTC assertion check on Windows development environments"""
    try:
        return original_utc_tzinfo(conn)
    except AssertionError:
        # For Windows development, return UTC timezone without assertion
        import datetime
        return datetime.timezone.utc

pg_utils.utc_tzinfo_factory = utc_tzinfo_factory_patched

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT='/home/django/django_project/django_project/static'
STATIC_URL = '/static/'
MEDIA_ROOT = '/home/django/django_project/media'
MEDIA_URL='/media/'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# Allow Django from all hosts. This snippet is installed from
# /var/lib/digitalocean/allow_hosts.py

import os

# Find out what the IP addresses are at run time
# This is necessary because otherwise Gunicorn will reject the connections
def ip_addresses():
    ip_list = ['*','mcqgk.com','www.mcqgk.com','tutionplus.com','www.tutionplus.com','m.tutionplus.com' ]
    try:
        import netifaces
        for interface in netifaces.interfaces():
            addrs = netifaces.ifaddresses(interface)
            for x in (netifaces.AF_INET, netifaces.AF_INET6):
                if x in addrs:
                    ip_list.append(addrs[x][0]['addr'])
    except ImportError:
        # netifaces not available, use default hosts only
        pass
    return ip_list

# Discover our IP address
ALLOWED_HOSTS = ip_addresses()

