# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='b',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
