# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20210307_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polity',
            name='topic',
            field=models.CharField(blank=True, choices=[('question-answare', 'question-answare')], db_index=True, default='question-answare', max_length=18, null=True),
        ),
    ]
