# Generated by Django 3.0 on 2026-02-02 17:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('mock_type', models.CharField(choices=[('mini', 'mini'), ('sectional', 'sectional'), ('subject', 'subject'), ('full', 'full'), ('practice', 'practice'), ('learning', 'learning')], db_index=True, default='full', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('config_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MockTestTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_mode', models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], db_index=True, default='auto', max_length=10)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='mocktest.MockTest')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='mocktest.Tab')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('mock_test', 'tab')},
            },
        ),
        migrations.CreateModel(
            name='MockDistributionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=150)),
                ('chapter', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('sub_chapter', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('section', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('difficulty', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('question_type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('question_count', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('mock_test_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='mocktest.MockTestTab')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_id', models.IntegerField(db_index=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('marks', models.FloatField(default=1.0)),
                ('negative_marks', models.FloatField(default=0.0)),
                ('added_manually', models.BooleanField(db_index=True, default=False)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.MockTest')),
                ('mock_test_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.MockTestTab')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('mock_test', 'mcq_id')},
            },
        ),
    ]
