# Generated by Django 3.0 on 2026-02-17 14:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0006_mockdistributionrule_mcq_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('ALL INDIA', 'ALL INDIA'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('ARUNACHAL PRADESH', 'ARUNACHAL PRADESH'), ('ASSAM', 'ASSAM'), ('BIHAR', 'BIHAR'), ('CHHATTISGARH', 'CHHATTISGARH'), ('GOA', 'GOA'), ('GUJARAT', 'GUJARAT'), ('HARYANA', 'HARYANA'), ('HIMACHAL PRADESH', 'HIMACHAL PRADESH'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('MIZORAM', 'MIZORAM'), ('NAGALAND', 'NAGALAND'), ('ODISHA', 'ODISHA'), ('PUNJAB', 'PUNJAB'), ('RAJASTHAN', 'RAJASTHAN'), ('SIKKIM', 'SIKKIM'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UTTAR PRADESH', 'UTTAR PRADESH'), ('UTTARAKHAND', 'UTTARAKHAND'), ('WEST BENGAL', 'WEST BENGAL'), ('ANDAMAN AND NICOBAR ISLANDS', 'ANDAMAN AND NICOBAR ISLANDS'), ('CHANDIGARH', 'CHANDIGARH'), ('DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU'), ('DELHI', 'DELHI'), ('JAMMU AND KASHMIR', 'JAMMU AND KASHMIR'), ('LADAKH', 'LADAKH'), ('LAKSHADWEEP', 'LAKSHADWEEP'), ('PUDUCHERRY', 'PUDUCHERRY')], db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('mock_tests', models.ManyToManyField(blank=True, related_name='exam_relations', to='mocktest.MockTest')),
            ],
            options={
                'ordering': ('-year', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExamSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mock_tests', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('total_tabs', models.PositiveIntegerField(default=0)),
                ('total_distribution_rules', models.PositiveIntegerField(default=0)),
                ('total_question_objects', models.PositiveIntegerField(default=0)),
                ('full_mocks_count', models.PositiveIntegerField(default=0)),
                ('sectional_mocks_count', models.PositiveIntegerField(default=0)),
                ('mini_mocks_count', models.PositiveIntegerField(default=0)),
                ('practice_mocks_count', models.PositiveIntegerField(default=0)),
                ('learning_mocks_count', models.PositiveIntegerField(default=0)),
                ('active_mocks_count', models.PositiveIntegerField(default=0)),
                ('inactive_mocks_count', models.PositiveIntegerField(default=0)),
                ('earliest_mock_created', models.DateTimeField(blank=True, null=True)),
                ('latest_mock_created', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='mocktest.Exam')),
            ],
            options={
                'ordering': ('-updated_at', 'exam'),
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='mocktest.Segment'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('segment', 'name', 'year', 'state')},
        ),
    ]
