# Generated by Django 3.0 on 2026-04-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0007_auto_20260217_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestquestion',
            name='correct_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
