# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcq',
            name='mythology',
            field=models.BooleanField(default=False),
        ),
    ]
