# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-07 16:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210307_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='polity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_now', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '3'), ('41', '41')], db_index=True, default='2018', max_length=10, null=True)),
                ('topic', models.CharField(blank=True, choices=[('question-answare', 'question-answare')], db_index=True, default='question-answare', max_length=15, null=True)),
                ('subtopic', models.CharField(blank=True, choices=[('question-answare', 'question-answare')], db_index=True, default='mcq', max_length=15, null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('question', models.TextField(default='')),
                ('option_1', models.CharField(max_length=250)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('option_4', models.CharField(blank=True, max_length=200, null=True)),
                ('option_5', models.CharField(blank=True, max_length=200, null=True)),
                ('ans', models.IntegerField(default=1)),
                ('year_exam', models.CharField(max_length=250)),
                ('extra', models.TextField(blank=True, default='', null=True)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='total_polity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_polity', models.IntegerField(db_index=True, default=3)),
                ('total_polity_page', models.IntegerField(db_index=True, default=3)),
                ('one', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
