# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20210308_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='polity',
            name='subtopic_more',
            field=models.CharField(blank=True, choices=[('more', 'more')], db_index=True, default='more', max_length=15, null=True),
        ),
    ]
