# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-08 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_polity_subtopic_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polity',
            name='subtopic_more',
        ),
        migrations.AddField(
            model_name='polity',
            name='subtopic_2',
            field=models.CharField(blank=True, choices=[('more', 'more')], db_index=True, default='more', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='subtopic',
            field=models.CharField(blank=True, choices=[('mcq', 'mcq')], db_index=True, default='mcq', max_length=20, null=True),
        ),
    ]
