# Generated by Django 3.0 on 2026-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20210308_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='biology',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], db_index=True, default='easy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biology',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='biology',
            name='mocktest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], db_index=True, default='easy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='mocktest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='economics',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], db_index=True, default='easy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='economics',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='economics',
            name='mocktest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='geography',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], db_index=True, default='easy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='geography',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='geography',
            name='mocktest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], db_index=True, default='easy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='mocktest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='physics',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], db_index=True, default='easy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='physics',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='physics',
            name='mocktest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='polity',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], db_index=True, default='easy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='polity',
            name='home',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='polity',
            name='mocktest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='biology',
            name='option_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='biology',
            name='option_2',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='biology',
            name='option_3',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='biology',
            name='option_4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='biology',
            name='option_5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='option_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='option_2',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='option_3',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='option_4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='option_5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='economics',
            name='option_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='economics',
            name='option_2',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='economics',
            name='option_3',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='economics',
            name='option_4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='economics',
            name='option_5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='option_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='geography',
            name='option_2',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='geography',
            name='option_3',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='geography',
            name='option_4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='option_5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='option_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='history',
            name='option_2',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='history',
            name='option_3',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='history',
            name='option_4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='option_5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='physics',
            name='option_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='physics',
            name='option_2',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='physics',
            name='option_3',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='physics',
            name='option_4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='physics',
            name='option_5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='option_1',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='polity',
            name='option_2',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='polity',
            name='option_3',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='polity',
            name='option_4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='polity',
            name='option_5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
