# Generated by Django 3.0 on 2026-01-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_mcq_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcq_info_2026',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mcq', models.IntegerField(db_index=True, default=3)),
                ('total_mcq_page', models.IntegerField(db_index=True, default=3)),
                ('month_list', models.TextField(blank=True, default='', null=True)),
                ('January', models.TextField(blank=True, default='', null=True)),
                ('February', models.TextField(blank=True, default='', null=True)),
                ('March', models.TextField(blank=True, default='', null=True)),
                ('April', models.TextField(blank=True, default='', null=True)),
                ('May', models.TextField(blank=True, default='', null=True)),
                ('June', models.TextField(blank=True, default='', null=True)),
                ('July', models.TextField(blank=True, default='', null=True)),
                ('August', models.TextField(blank=True, default='', null=True)),
                ('September', models.TextField(blank=True, default='', null=True)),
                ('October', models.TextField(blank=True, default='', null=True)),
                ('November', models.TextField(blank=True, default='', null=True)),
                ('December', models.TextField(blank=True, default='', null=True)),
                ('January_page', models.CharField(blank=True, max_length=5, null=True)),
                ('February_page', models.CharField(blank=True, max_length=5, null=True)),
                ('March_page', models.CharField(blank=True, max_length=5, null=True)),
                ('April_page', models.CharField(blank=True, max_length=5, null=True)),
                ('May_page', models.CharField(blank=True, max_length=5, null=True)),
                ('June_page', models.CharField(blank=True, max_length=5, null=True)),
                ('July_page', models.CharField(blank=True, max_length=5, null=True)),
                ('August_page', models.CharField(blank=True, max_length=5, null=True)),
                ('September_page', models.CharField(blank=True, max_length=5, null=True)),
                ('October_page', models.CharField(blank=True, max_length=5, null=True)),
                ('November_page', models.CharField(blank=True, max_length=5, null=True)),
                ('December_page', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mcq',
            name='year_now',
            field=models.CharField(blank=True, choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2026', '2026')], db_index=True, default='2018', max_length=10, null=True),
        ),
    ]
