# Generated by Django 3.0 on 2026-01-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_add_mcq_info_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='is_live',
            field=models.BooleanField(db_index=True, default=True, help_text='Check to show on webpage'),
        ),
    ]
