# Generated by Django 3.0 on 2026-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_add_is_live_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_affairs',
            name='is_live',
            field=models.BooleanField(db_index=True, default=True, help_text='Check to show on webpage'),
        ),
    ]
