# Generated by Django 3.0 on 2026-01-25 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20260125_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='currentaffairs_mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_now', models.CharField(blank=True, choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], db_index=True, default='2018', max_length=10, null=True)),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], db_index=True, default='December', max_length=15, null=True)),
                ('day', models.DateField(db_index=True, default=datetime.date.today)),
                ('creation_time', models.TimeField(blank=True, null=True)),
                ('question', models.TextField(default='')),
                ('option_1', models.CharField(max_length=250)),
                ('option_2', models.CharField(max_length=200)),
                ('option_3', models.CharField(max_length=200)),
                ('option_4', models.CharField(blank=True, max_length=200, null=True)),
                ('option_5', models.CharField(blank=True, max_length=200, null=True)),
                ('ans', models.IntegerField(default=1)),
                ('appointment', models.BooleanField(default=False)),
                ('Art_Culture', models.BooleanField(db_index=True, default=False)),
                ('Awards_Honours', models.BooleanField(db_index=True, default=False)),
                ('Business_Economy_Banking', models.BooleanField(db_index=True, default=False)),
                ('Defence', models.BooleanField(db_index=True, default=False)),
                ('Environment', models.BooleanField(db_index=True, default=False)),
                ('Government_Schemes', models.BooleanField(default=False)),
                ('International', models.BooleanField(db_index=True, default=False)),
                ('medical', models.BooleanField(db_index=True, default=False)),
                ('National', models.BooleanField(db_index=True, default=False)),
                ('obituary', models.BooleanField(default=False)),
                ('Persons_in_News', models.BooleanField(db_index=True, default=False)),
                ('rank', models.BooleanField(default=False)),
                ('Science_Techonlogy', models.BooleanField(db_index=True, default=False)),
                ('Sports', models.BooleanField(db_index=True, default=False)),
                ('State', models.BooleanField(db_index=True, default=False)),
                ('static_gk', models.BooleanField(default=False)),
                ('important_day', models.BooleanField(default=False)),
                ('agreement', models.BooleanField(default=False)),
                ('mythology', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(db_index=True, default=True, help_text='Check to show on webpage')),
                ('extra', models.TextField(blank=True, default='', null=True)),
                ('new_id', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.RenameModel(
            old_name='current_affairs',
            new_name='currentaffairs_descriptive',
        ),
        migrations.DeleteModel(
            name='mcq',
        ),
    ]
