# Generated by Django 3.0 on 2026-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_rename_info_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='Source URL or leave blank for default prompt (e.g., https://example.com/news)', max_length=500)),
                ('prompt_type', models.CharField(choices=[('mcq', 'MCQ'), ('descriptive', 'Descriptive')], help_text='Type of prompt: MCQ or Descriptive', max_length=20)),
                ('prompt_text', models.TextField(help_text='The actual prompt to send to LLM. Use {title} and {body} as placeholders.')),
                ('is_default', models.BooleanField(default=False, help_text='Check if this is the default prompt for this type')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to disable this prompt without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='System', help_text='User who created this prompt', max_length=100)),
            ],
            options={
                'verbose_name': 'LLM Prompt',
                'verbose_name_plural': 'LLM Prompts',
                'ordering': ['-is_default', 'source_url', 'prompt_type'],
                'unique_together': {('source_url', 'prompt_type')},
            },
        ),
    ]
