# Generated by Django 3.0 on 2026-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_llmprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the news source (e.g., GK Today)', max_length=200)),
                ('url', models.URLField(help_text='Full URL of the news source', unique=True)),
                ('content_type', models.CharField(choices=[('mcq', 'Current Affairs MCQ'), ('descriptive', 'Current Affairs Descriptive')], help_text='What type of content to scrape from this source', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Check to enable scraping from this source')),
                ('description', models.TextField(blank=True, help_text='Notes about this source (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'ordering': ['content_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='newssource',
            index=models.Index(fields=['is_active', 'content_type'], name='bank_newsso_is_acti_f7c3b9_idx'),
        ),
    ]
