# Generated by Django 3.0 on 2026-01-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_auto_20260125_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLMPrompt',
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
    ]
