# Generated by Django 3.0 on 2026-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_auto_20260125_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
