# Generated by Copilot on 2026-01-30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_job_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='canonical_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Confidence score for canonical match', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='canonical_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
