# Generated by Django 3.0 on 2026-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_auto_20260202_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='llm_used',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='math',
            name='validation_status',
            field=models.CharField(choices=[('not_validated', 'not validated'), ('validated', 'validated')], db_index=True, default='not_validated', max_length=20),
        ),
        migrations.AddField(
            model_name='reasoning',
            name='llm_used',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='reasoning',
            name='validation_status',
            field=models.CharField(choices=[('not_validated', 'not validated'), ('validated', 'validated')], db_index=True, default='not_validated', max_length=20),
        ),
    ]
