# Generated by Django 3.0 on 2026-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_auto_20260427_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='rules_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
