# Generated by Django 3.0 on 2026-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_add_rules_html_to_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='exam_and_year',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
