# Generated by Django 3.0 on 2026-04-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_add_exam_and_year_to_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='from_json',
            field=models.BooleanField(default=False),
        ),
    ]
