# Generated by Django 3.0 on 2026-04-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_add_from_json_to_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='rule_based_explanation',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
