# Generated by Django 3.0 on 2026-05-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_add_rule_based_explanation_to_math'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='chapter',
            field=models.CharField(blank=True, choices=[('profit_n_loss', 'profit_n_loss'), ('squre_n_cube', 'squre_n_cube'), ('simplification', 'simplification'), ('average', 'average'), ('percentage', 'percentage'), ('problem_on_age', 'problem_on_age'), ('ratio_n_proportion', 'ratio_n_proportion'), ('partnership', 'partnership'), ('time_n_work', 'time_n_work'), ('pipe_cistern', 'pipe_cistern'), ('time_n_distance', 'time_n_distance'), ('boats_n_stream', 'boats_n_stream'), ('alligation_n_mixture', 'alligation_n_mixture'), ('simple_interest', 'simple_interest'), ('compound_interest', 'compound_interest'), ('volume_n_surface_area', 'volume_n_surface_area'), ('probability', 'probability'), ('permutation_combination', 'permutation_combination'), ('bar_graph', 'bar_graph'), ('pie_charts', 'pie_charts'), ('line_graph', 'line_graph')], db_index=True, default='any', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='rule_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(choices=[('profit_n_loss', 'profit_n_loss'), ('squre_n_cube', 'squre_n_cube'), ('simplification', 'simplification'), ('average', 'average'), ('percentage', 'percentage'), ('problem_on_age', 'problem_on_age'), ('ratio_n_proportion', 'ratio_n_proportion'), ('partnership', 'partnership'), ('time_n_work', 'time_n_work'), ('pipe_cistern', 'pipe_cistern'), ('time_n_distance', 'time_n_distance'), ('boats_n_stream', 'boats_n_stream'), ('alligation_n_mixture', 'alligation_n_mixture'), ('simple_interest', 'simple_interest'), ('compound_interest', 'compound_interest'), ('volume_n_surface_area', 'volume_n_surface_area'), ('probability', 'probability'), ('permutation_combination', 'permutation_combination'), ('bar_graph', 'bar_graph'), ('pie_charts', 'pie_charts'), ('line_graph', 'line_graph')], db_index=True, max_length=50)),
                ('rule_name', models.CharField(choices=[('Rule 1', 'Rule 1'), ('Rule 2', 'Rule 2'), ('Rule 3', 'Rule 3'), ('Rule 4', 'Rule 4'), ('Rule 5', 'Rule 5'), ('Rule 6', 'Rule 6'), ('Rule 7', 'Rule 7'), ('Rule 8', 'Rule 8'), ('Rule 9', 'Rule 9'), ('Rule 10', 'Rule 10'), ('Rule 11', 'Rule 11'), ('Rule 12', 'Rule 12'), ('Rule 13', 'Rule 13'), ('Rule 14', 'Rule 14'), ('Rule 15', 'Rule 15'), ('Rule 16', 'Rule 16'), ('Rule 17', 'Rule 17'), ('Rule 18', 'Rule 18'), ('Rule 19', 'Rule 19'), ('Rule 20', 'Rule 20'), ('Rule 21', 'Rule 21'), ('Rule 22', 'Rule 22'), ('Rule 23', 'Rule 23'), ('Rule 24', 'Rule 24'), ('Rule 25', 'Rule 25'), ('Rule 26', 'Rule 26'), ('Rule 27', 'Rule 27'), ('Rule 28', 'Rule 28'), ('Rule 29', 'Rule 29'), ('Rule 30', 'Rule 30'), ('Rule 31', 'Rule 31'), ('Rule 32', 'Rule 32'), ('Rule 33', 'Rule 33'), ('Rule 34', 'Rule 34'), ('Rule 35', 'Rule 35'), ('Rule 36', 'Rule 36'), ('Rule 37', 'Rule 37'), ('Rule 38', 'Rule 38'), ('Rule 39', 'Rule 39'), ('Rule 40', 'Rule 40'), ('Rule 41', 'Rule 41'), ('Rule 42', 'Rule 42'), ('Rule 43', 'Rule 43'), ('Rule 44', 'Rule 44'), ('Rule 45', 'Rule 45'), ('Rule 46', 'Rule 46'), ('Rule 47', 'Rule 47'), ('Rule 48', 'Rule 48'), ('Rule 49', 'Rule 49'), ('Rule 50', 'Rule 50')], max_length=20)),
                ('rule_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['chapter', 'rule_name'],
                'unique_together': {('chapter', 'rule_name')},
            },
        ),
        migrations.AddField(
            model_name='math',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.rule_math'),
        ),
    ]
