# Generated by Django 3.0 on 2026-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0030_auto_20260502_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule_math',
            name='rule_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
