# Generated by Django 3.0 on 2026-05-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_rule_math_rule_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='math_translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi')], db_index=True, max_length=5)),
                ('question', models.TextField(blank=True, null=True)),
                ('a', models.CharField(blank=True, max_length=500, null=True)),
                ('b', models.CharField(blank=True, max_length=500, null=True)),
                ('c', models.CharField(blank=True, max_length=500, null=True)),
                ('d', models.CharField(blank=True, max_length=500, null=True)),
                ('e', models.CharField(blank=True, max_length=500, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('shortcut', models.TextField(blank=True, null=True)),
                ('math', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bank.math')),
            ],
            options={
                'ordering': ['math', 'language'],
                'unique_together': {('math', 'language')},
            },
        ),
    ]
