# Generated by Django 3.0 on 2026-05-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0032_math_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_translation',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
