# Generated by Django 3.0 on 2026-05-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0033_add_extra_to_math_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='math_translation',
            name='rule_based_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='rule_math_translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi')], db_index=True, max_length=5)),
                ('rule_html', models.TextField(blank=True, null=True)),
                ('rule_content', models.TextField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bank.rule_math')),
            ],
            options={
                'unique_together': {('rule', 'language')},
            },
        ),
    ]
