# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20190501_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcq',
            name='important_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcq',
            name='mythology',
            field=models.BooleanField(default=False),
        ),
    ]
