# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20190501_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='question_no',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
