# Generated by Django 3.0 on 2026-01-24 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffairsGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_mcq', models.TextField(blank=True, help_text='Generated MCQ content', null=True)),
                ('generated_descriptive', models.TextField(blank=True, help_text='Generated descriptive content', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MathProblemGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField(help_text='Math expression to convert to LaTeX')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('latex_output', models.TextField(blank=True, null=True)),
                ('generated_mcqs', models.TextField(blank=True, help_text='Generated MCQs in JSON format', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('polity', 'Polity'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('math', 'Math'), ('other', 'Other')], default='other', max_length=50)),
                ('pdf_file', models.FileField(upload_to='genai/pdfs/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_pages', models.IntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('pdf_to_mcq', 'PDF to MCQ'), ('current_affairs_mcq', 'Current Affairs MCQ'), ('current_affairs_descriptive', 'Current Affairs Descriptive'), ('math_to_latex', 'Math to LaTeX'), ('math_mcq_batch', 'Math MCQ Batch'), ('pdf_extraction', 'PDF Text Extraction')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.TextField(blank=True, help_text='Input parameters as JSON', null=True)),
                ('output_data', models.TextField(blank=True, help_text='Generated output as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pdf_upload', models.ForeignKey(blank=True, help_text='Associated PDF upload', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genai.PDFUpload')),
            ],
            options={
                'verbose_name': 'Processing Task',
                'verbose_name_plural': 'Processing Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
