# Generated by Django 3.0 on 2026-01-24 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('mcq_fetch', 'MCQ Fetch'), ('current_affairs_fetch', 'Current Affairs Fetch'), ('both', 'Both MCQ & Current Affairs')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('mcq_status', models.CharField(blank=True, default='', max_length=100)),
                ('current_affairs_status', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('log_details', models.TextField(blank=True, help_text='Detailed log as JSON', null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['-created_at'], name='genai_proce_created_2314ff_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['status', '-created_at'], name='genai_proce_status_b088f6_idx'),
        ),
    ]
