# Generated by Django 3.0 on 2026-01-24 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genai', '0002_auto_20260125_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('mcq', 'MCQ Source'), ('current_affairs', 'Current Affairs Source')], max_length=20)),
                ('url', models.URLField(help_text='Enter the full URL to fetch content from', max_length=500)),
                ('name', models.CharField(help_text='Display name for this source', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of this source', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Source',
                'verbose_name_plural': 'Content Sources',
                'ordering': ['-created_at'],
                'unique_together': {('source_type', 'url')},
            },
        ),
    ]
