# Generated by Django 3.0 on 2026-01-24 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0003_contentsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='pdf_upload',
            field=models.ForeignKey(blank=True, help_text='PDF file if this is a PDF processing task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genai.PDFUpload'),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='task_type',
            field=models.CharField(choices=[('mcq_fetch', 'MCQ Fetch from URL'), ('current_affairs_fetch', 'Current Affairs Fetch from URL'), ('both', 'Both MCQ & Current Affairs from URL'), ('pdf_mcq', 'MCQ Generation from PDF'), ('pdf_current_affairs', 'Current Affairs Generation from PDF')], max_length=50),
        ),
    ]
