# Generated by Django 3.0 on 2026-01-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0004_auto_20260125_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='source_type',
            field=models.CharField(choices=[('currentaffairs_mcq', 'Current Affairs MCQ Source'), ('current_affairs_descriptive', 'Current Affairs Descriptive Source')], max_length=40),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='task_type',
            field=models.CharField(choices=[('currentaffairs_mcq_fetch', 'Current Affairs MCQ Fetch from URL'), ('current_affairs_descriptive_fetch', 'Current Affairs Descriptive Fetch from URL'), ('both', 'Both MCQ & Current Affairs from URL'), ('pdf_currentaffairs_mcq', 'Current Affairs MCQ Generation from PDF'), ('pdf_current_affairs_descriptive', 'Current Affairs Descriptive Generation from PDF')], max_length=50),
        ),
    ]
