# Generated by Django 3.0 on 2026-01-25 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genai', '0006_auto_20260125_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True, help_text='Source URL or leave blank for default prompt (e.g., https://example.com/news)', max_length=500, null=True)),
                ('prompt_type', models.CharField(choices=[('mcq', 'MCQ'), ('descriptive', 'Descriptive')], help_text='Type of prompt: MCQ or Descriptive', max_length=20)),
                ('prompt_text', models.TextField(help_text='The actual prompt to send to LLM. Use {title} and {content} as placeholders.')),
                ('is_default', models.BooleanField(default=False, help_text='Check if this is the default prompt for this type')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to disable this prompt without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Prompt',
                'verbose_name_plural': 'LLM Prompts',
                'ordering': ['-is_default', 'source_url', 'prompt_type'],
                'unique_together': {('source_url', 'prompt_type')},
            },
        ),
    ]
