# Generated by Django 3.0 on 2026-01-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0008_contentsource_content_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='skip_scraping',
            field=models.BooleanField(default=False, help_text='Skip web scraping and send URLs directly to LLM with prompt'),
        ),
    ]
