# Generated by Django 3.0 on 2026-01-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0009_processinglog_skip_scraping'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level for generated content', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='end_page',
            field=models.IntegerField(blank=True, help_text='End page for PDF processing', null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='num_items',
            field=models.IntegerField(blank=True, default=5, help_text='Number of MCQs/Descriptive answers to generate', null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='output_format',
            field=models.CharField(blank=True, choices=[('json', 'JSON'), ('markdown', 'Markdown'), ('text', 'Plain Text')], default='json', help_text='Format for output (MCQ/Descriptive)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='start_page',
            field=models.IntegerField(blank=True, help_text='Start page for PDF processing', null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='subject',
            field=models.CharField(blank=True, choices=[('polity', 'Polity'), ('economics', 'Economics'), ('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('history', 'History'), ('geography', 'Geography'), ('biology', 'Biology'), ('other', 'Other')], db_index=True, default='other', help_text='Subject for routing to subject-specific processor', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='task_type',
            field=models.CharField(choices=[('currentaffairs_mcq_fetch', 'Current Affairs MCQ Fetch from URL'), ('currentaffairs_descriptive_fetch', 'Current Affairs Descriptive Fetch from URL'), ('both', 'Both MCQ & Current Affairs from URL'), ('pdf_currentaffairs_mcq', 'Current Affairs MCQ Generation from PDF'), ('pdf_currentaffairs_descriptive', 'Current Affairs Descriptive Generation from PDF'), ('pdf_to_mcq', 'PDF to Generic MCQ'), ('pdf_to_descriptive', 'PDF to Generic Descriptive'), ('pdf_to_polity', 'PDF to Polity MCQ'), ('pdf_to_economics', 'PDF to Economics MCQ'), ('pdf_to_math', 'PDF to Math MCQ'), ('pdf_to_physics', 'PDF to Physics MCQ'), ('pdf_to_chemistry', 'PDF to Chemistry MCQ'), ('pdf_to_history', 'PDF to History MCQ'), ('pdf_to_geography', 'PDF to Geography MCQ'), ('pdf_to_biology', 'PDF to Biology MCQ')], max_length=50),
        ),
    ]
