# Generated by Django 3.0 on 2026-01-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0010_auto_20260126_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='ca_auto_date',
            field=models.BooleanField(default=False, help_text='If True, LLM decides date/year from content'),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='ca_date',
            field=models.DateField(blank=True, help_text='Date for current affairs (if provided by user)', null=True),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='ca_year',
            field=models.CharField(blank=True, choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], help_text='Year for current affairs', max_length=10, null=True),
        ),
    ]
