# Generated by Django 3.0 on 2026-01-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0011_auto_20260127_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='send_url_directly',
            field=models.BooleanField(default=False, help_text='Send URL directly to LLM without fetching content (takes precedence over skip_scraping)'),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='skip_scraping',
            field=models.BooleanField(default=False, help_text='Skip intelligent article extraction and send downloaded content to LLM'),
        ),
    ]
