# Generated by Django 3.0 on 2026-01-27 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genai', '0014_processinglog_use_playwright'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_table', models.CharField(choices=[('currentaffairs_mcq', 'Current Affairs MCQ'), ('currentaffairs_descriptive', 'Current Affairs Descriptive'), ('current_affairs_slide', 'Current Affairs Slide'), ('total', 'Total'), ('total_english', 'Total English'), ('total_math', 'Total Math'), ('total_job', 'Total Job'), ('total_job_category', 'Total Job Category'), ('total_job_state', 'Total Job State'), ('home', 'Home'), ('topic', 'Topic'), ('math', 'Math'), ('job', 'Job'), ('the_hindu_word_Header1', 'The Hindu Word Header 1'), ('the_hindu_word_Header2', 'The Hindu Word Header 2'), ('the_hindu_word_list1', 'The Hindu Word List 1'), ('the_hindu_word_list2', 'The Hindu Word List 2'), ('the_economy_word_Header1', 'The Economy Word Header 1'), ('the_economy_word_Header2', 'The Economy Word Header 2'), ('the_economy_word_list1', 'The Economy Word List 1'), ('the_economy_word_list2', 'The Economy Word List 2')], help_text='Select which bank model table to import data to', max_length=50)),
                ('json_data', models.TextField(help_text='Paste JSON array of objects here. Each object represents a record to be imported.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JSON Import',
                'verbose_name_plural': 'JSON Imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
