# Generated by Django 3.0 on 2026-01-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0016_remove_jsonimport_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonimport',
            name='to_table',
            field=models.CharField(choices=[('polity', 'Polity'), ('history', 'History'), ('geography', 'Geography'), ('economics', 'Economics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('reasoning', 'Reasoning'), ('error', 'Error/Grammar'), ('mcq', 'MCQ General'), ('currentaffairs_mcq', 'Current Affairs MCQ'), ('currentaffairs_descriptive', 'Current Affairs Descriptive'), ('current_affairs_slide', 'Current Affairs Slide'), ('total', 'Total'), ('total_english', 'Total English'), ('total_math', 'Total Math'), ('total_job', 'Total Job'), ('total_job_category', 'Total Job Category'), ('total_job_state', 'Total Job State'), ('home', 'Home'), ('topic', 'Topic'), ('math', 'Math'), ('job', 'Job'), ('the_hindu_word_Header1', 'The Hindu Word Header 1'), ('the_hindu_word_Header2', 'The Hindu Word Header 2'), ('the_hindu_word_list1', 'The Hindu Word List 1'), ('the_hindu_word_list2', 'The Hindu Word List 2'), ('the_economy_word_Header1', 'The Economy Word Header 1'), ('the_economy_word_Header2', 'The Economy Word Header 2'), ('the_economy_word_list1', 'The Economy Word List 1'), ('the_economy_word_list2', 'The Economy Word List 2')], help_text='Select which bank model table to import data to', max_length=50),
        ),
        migrations.AlterField(
            model_name='mathproblemgeneration',
            name='expression',
            field=models.TextField(blank=True, help_text='Math expression to convert to LaTeX (optional)', null=True),
        ),
    ]
