# Generated by Django 3.0 on 2026-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0017_auto_20260128_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathproblemgeneration',
            name='chapter',
            field=models.CharField(blank=True, help_text='Chapter name (optional, can be decided by LLM)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mathproblemgeneration',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF file for math problem extraction', null=True, upload_to='math/pdfs/'),
        ),
    ]
