# Generated by Django 3.0 on 2026-05-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai', '0019_jobfetch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprompt',
            name='prompt_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('descriptive', 'Descriptive'), ('rule_extraction', 'Rule Extraction')], help_text='Type of prompt: MCQ or Descriptive', max_length=20),
        ),
    ]
