# Generated by Django 3.0 on 2026-02-18 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0007_auto_20260217_2024'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='mocktest.MockTest')),
                ('mock_test_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='mocktest.MockTestTab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='students.StudentProfile')),
            ],
            options={
                'ordering': ('-started_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('final_selected_option', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('first_attempt_time_seconds', models.IntegerField(default=0)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('option_change_count', models.IntegerField(default=0)),
                ('mark_for_review_count', models.IntegerField(default=0)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('was_ever_marked_for_review', models.BooleanField(default=False)),
                ('confusion_flag', models.BooleanField(default=False)),
                ('confusion_score', models.FloatField(default=0)),
                ('review_outcome_type', models.CharField(choices=[('never_reviewed', 'never_reviewed'), ('reviewed_skipped', 'reviewed_skipped'), ('reviewed_correct', 'reviewed_correct'), ('reviewed_wrong', 'reviewed_wrong')], default='never_reviewed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mock_test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='mocktest.MockTestQuestion')),
                ('section_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='students.SectionAttempt')),
            ],
            options={
                'ordering': ('mock_test_question', 'section_attempt', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['section_attempt', 'mock_test_question'], name='students_qu_section_045130_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('section_attempt', 'mock_test_question')},
        ),
    ]
