# Generated by Django 3.0 on 2026-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20260218_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionattempt',
            name='average_confusion_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sectionattempt',
            name='total_confused_questions',
            field=models.IntegerField(default=0),
        ),
    ]
