# Generated by Django 3.0 on 2026-02-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0007_auto_20260217_2024'),
        ('students', '0003_sectionattempt_confusion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_confused_questions', models.IntegerField(default=0)),
                ('confusion_index', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_attempts', to='mocktest.Exam')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocktest.MockTest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_attempts', to='students.StudentProfile')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['student', 'mock_test'], name='students_m_student_b2cdac_idx'),
        ),
    ]
