# Generated by Django 3.0 on 2026-02-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0007_auto_20260217_2024'),
        ('students', '0004_mocktestattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=150)),
                ('strength_score', models.FloatField(default=0)),
                ('previous_strength_score', models.FloatField(default=0)),
                ('mastery_streak', models.PositiveIntegerField(default=0)),
                ('average_confusion_index', models.FloatField(default=0)),
                ('total_confused_questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='mocktest.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='students.StudentProfile')),
            ],
            options={
                'ordering': ('-updated_at', 'id'),
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='subjectperformance',
            index=models.Index(fields=['student', 'exam', 'subject'], name='students_s_student_5a82d4_idx'),
        ),
    ]
