# Generated by Django 3.0 on 2026-02-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_subjectperformance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mocktestattempt',
            name='students_m_student_b2cdac_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectperformance',
            name='students_s_student_5a82d4_idx',
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['student', 'mock_test'], name='students_mo_student_1c56e9_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectperformance',
            index=models.Index(fields=['student', 'exam', 'subject'], name='students_su_student_71ea0e_idx'),
        ),
    ]
