# Generated by Django 3.0 on 2026-02-18 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20260218_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('success', 'success'), ('failed', 'failed'), ('refunded', 'refunded')], db_index=True, default='initiated', max_length=12)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('metadata', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mocktestattempt',
            name='total_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='sectionattempt',
            name='mock_test_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='students.MockTestAttempt'),
        ),
        migrations.AddField(
            model_name='sectionattempt',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['mock_test', 'total_score'], name='students_mo_mock_te_10f236_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['section_attempt'], name='students_qu_section_f8598d_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['mock_test_question'], name='students_qu_mock_te_e6de65_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionattempt',
            index=models.Index(fields=['student', 'mock_test'], name='students_se_student_51d0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionattempt',
            index=models.Index(fields=['mock_test_attempt', 'mock_test_tab'], name='students_se_mock_te_9584d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='mocktestattempt',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('student', 'mock_test'), name='uniq_active_attempt_per_student_mock'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.StudentProfile'),
        ),
    ]
