# Generated by Django 3.0 on 2026-02-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20260219_0122'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sectionattempt',
            name='students_se_student_51d0e5_idx',
        ),
        migrations.RemoveField(
            model_name='sectionattempt',
            name='mock_test',
        ),
        migrations.RemoveField(
            model_name='sectionattempt',
            name='student',
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['is_active'], name='students_mo_is_acti_f11c93_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(condition=models.Q(confusion_flag=True), fields=['section_attempt'], name='qa_confused_by_section_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionattempt',
            index=models.Index(fields=['mock_test_attempt'], name='students_se_mock_te_012abe_idx'),
        ),
    ]
