# Generated by Django 3.0 on 2026-04-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0007_auto_20260217_2024'),
        ('students', '0009_backfill_section_mock_test_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=150)),
                ('chapter', models.CharField(db_index=True, max_length=150)),
                ('sub_chapter', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('section', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('avg_time_spent', models.FloatField(default=0)),
                ('avg_confusion_score', models.FloatField(default=0)),
                ('strength_score', models.FloatField(default=0)),
                ('weak_flag', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to='mocktest.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to='students.StudentProfile')),
            ],
        ),
        migrations.AddIndex(
            model_name='topicperformance',
            index=models.Index(fields=['student', 'exam'], name='students_to_student_f36d33_idx'),
        ),
        migrations.AddIndex(
            model_name='topicperformance',
            index=models.Index(fields=['student', 'exam', 'subject'], name='students_to_student_01da74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicperformance',
            unique_together={('student', 'exam', 'subject', 'chapter', 'sub_chapter', 'section')},
        ),
    ]
