# Generated by Django 3.0 on 2026-04-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0008_auto_20260413_1541'),
        ('students', '0010_topic_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestattempt',
            name='mocktest_attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='StudentRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(choices=[('mocktest', 'Mock Test'), ('tab', 'Tab / Section'), ('chapter', 'Chapter'), ('sub_chapter', 'Sub Chapter'), ('section', 'Section')], db_index=True, max_length=20)),
                ('rank_scope', models.CharField(db_index=True, help_text='Identifies the scope, e.g. tab name, chapter name, etc.', max_length=255)),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('percentile', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='mocktest.MockTest')),
                ('mock_test_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='students.MockTestAttempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='students.StudentProfile')),
            ],
            options={
                'ordering': ('rank_type', 'rank', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='studentranking',
            index=models.Index(fields=['mock_test', 'rank_type', 'rank_scope'], name='students_st_mock_te_6523e9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentranking',
            index=models.Index(fields=['student', 'rank_type'], name='students_st_student_aeb928_idx'),
        ),
        migrations.AddIndex(
            model_name='studentranking',
            index=models.Index(fields=['mock_test_attempt'], name='students_st_mock_te_b04838_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentranking',
            unique_together={('mock_test_attempt', 'rank_type', 'rank_scope')},
        ),
    ]
